language: rust
os: linux
dist: focal

jobs:
  include:
    - rust: stable
    - rust: nightly

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libclang1 linux-libc-dev

script:
  - make -C data/c_code -f Makefile
  - cargo test --all

notifications:
  email:
    on_success: never
