[package]
name = "hstrace"
version = "0.0.1"
authors = ["Mika Vatanen <blaind@blaind.net>"]
repository = "https://github.com/blaind/hstrace"
documentation = "https://docs.rs/hstrace"
description = "Syscall tracing from command line and as a library"
license = "Apache-2.0/MIT"
edition = "2018"
